language: node_js

node_js: lts/*

branches:
  only:
    - master

notifications:
  email: false

install:
  - travis_retry npm install

script:
  - npm test

after_success:
  - npm run build

jobs:
  include:
    - stage: release
      script:
        - npm run semantic-release