name: npm-publish

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          NPM_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          CI: true
